default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:<%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: localhost
  database: furima39994_development


test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima39994_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>